function t391_checkSize(recid){var el=$("#rec"+recid);var cover=el.find('.t-cover');var carrier=el.find('.t-cover__carrier');var filter=el.find('.t-cover__filter');var height=el.find('.t391__firstcol').height()+el.find('.t391__secondcol').height();if(window.matchMedia('(max-width: 960px)').matches){cover.css('height',height);carrier.css('height',height);filter.css('height',height)}}
t431_createTable=function(recid,tablehead,tabledata,tablecolsize,hastargetblank,btnstyles,t431__tdstyles,t431__thstyles,t431__oddrowstyles,t431__evenrowstyles){var t431__arrayColSize=t431_parseData(tablecolsize);var t431__arrayHead=t431_parseData(tablehead);var t431__arrayData=t431_parseData(tabledata);var t431__maxcolnumber=t431__findMaxRowLengthInTable(t431__arrayHead,t431__arrayData);var t431__colWidth=t431__setColumnsWidth(t431__arrayColSize,t431__maxcolnumber,recid);if(t431__colWidth[0].myText&&t431__colWidth[0].myText[t431__colWidth[0].myText.length-1]=="%"){for(var i=0;i<t431__colWidth.length;i++){t431__colWidth[i].myText=t431__colWidth[i].myText.slice(0,-1);t431__colWidth[i].myText+="vw"}}
var t431__container=$('#rec'+recid+' .t431 .t-container .t431__table');var t431__htmlTable="";if(t431__arrayHead){t431__htmlTable+=t431__generateHtml(recid,t431__arrayHead,"th",hastargetblank,t431__colWidth,btnstyles,t431__thstyles,null,null,t431__maxcolnumber)}
t431__container.append(t431__htmlTable);t431__htmlTable="";if(t431__arrayData){t431__htmlTable+=t431__generateHtml(recid,t431__arrayData,"td",hastargetblank,t431__colWidth,btnstyles,t431__tdstyles,t431__oddrowstyles,t431__evenrowstyles,t431__maxcolnumber)}
t431__container.append(t431__htmlTable)};t431_setHeadWidth=function(recid){if($(window).width()>960){var t431__tbody=$('#rec'+recid+' .t431 .t431__tbody');var t431__thead=$('#rec'+recid+' .t431 .t431__thead');t431__tbody.css("display","block");t431__thead.css("display","block");var t431__colWidth=$('#rec'+recid+' .t431 .t431__tbody tr:first').children().map(function(){return $(this).width()});if($('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').length>=3){var t431__verticalborder=$('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').slice(0,-2)}
$('#rec'+recid+' .t431 .t431__thead tr').children().each(function(i,v){if($(v).is(":last-child")){$(v).width(t431__colWidth[i]+(t431__tbody.width()-$('#rec'+recid+' .t431 .t431__tbody tr:first').width()))}else{$(v).width(t431__colWidth[i]+(+t431__verticalborder))}})}};t431__findMaxRowLengthInTable=function(arrayhead,arraydata){var t431__headmaxlength=0;var t431__datamaxlength=0;if(arrayhead){t431__headmaxlength=t431__findMaxRowLengInArray(arrayhead)}
if(arraydata){t431__datamaxlength=t431__findMaxRowLengInArray(arraydata)}
if(t431__datamaxlength>t431__headmaxlength){return t431__datamaxlength}else{return t431__headmaxlength}};t431__findMaxRowLengInArray=function(curarray){var t431__maxlength=0;for(var i=0;i<curarray.length;i++){if(curarray[i].length>t431__maxlength){t431__maxlength=curarray[i].length}}
return t431__maxlength};t431__setColumnsWidth=function(t431__colwidth,t431__colsnumber,recid){if(t431__colwidth){return t431__colwidth[0]}else{var t431__tablewidth=$('#rec'+recid+' .t431 .t-container .t-col').width();return(t431__tablewidth/t431__colsnumber+"px")}};t431__generateHtml=function(recid,arrayValues,coltag,hastargetblank,colWidth,btnstyles,colstyles,oddrowstyles,evenrowstyles,maxcolnumber){var t431__htmlpart="";if(coltag=="td"){var t431__theadorbodytag="tbody"}else{var t431__theadorbodytag="thead"}
t431__htmlpart+="<"+t431__theadorbodytag+" class=\"t431__"+t431__theadorbodytag+"\">";if($('#rec'+recid+' .t431 .t-container .t431__thead th').length>0&&$('#rec'+recid+' .t431 .t-container .t431__thead th').css("border-bottom-width")[0]!="0"){var t431__firstbodyrowstyle="border-top: 0 !important;"}
for(var i=0;i<arrayValues.length;i++){if(coltag=="td"){if((i+1)%2>0){t431__htmlpart+="<tr class=\"t431__oddrow\""+"style=\""+oddrowstyles+"\">"}else{t431__htmlpart+="<tr class=\"t431__evenrow\""+"style=\""+evenrowstyles+"\">"}}else{t431__htmlpart+="<tr>"}
var t431__addingcols=0;if(arrayValues[i].length<maxcolnumber){t431__addingcols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+t431__addingcols);j++){if(arrayValues[i][j]){if(Array.isArray(colWidth)&&colWidth[j]){var t431__curWidth=colWidth[j].myText}else{var t431__curWidth=colWidth}
if(i==0&&coltag=="td"){var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+t431__firstbodyrowstyle+"\">"}else{var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"}
if(arrayValues[i][j].myHref){var t431__tblank="";if(hastargetblank){var t431__tblank="target=\"_blank\""}
if(arrayValues[i][j].myHrefType=="link"){var t431__linkwithattr="<a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+">";var t431__linkclosetag="</a>"}else{var t431__linkwithattr="<div class=\"t431__btnwrapper\"><a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+" class=\"t-btn t-btn_sm\" style=\""+btnstyles+"\"><table style=\"width:100%; height:100%;\"><tr><td>";var t431__linkclosetag="</td></tr></table></a></div>"}
t431__htmlpart+=t431__colwithattr+t431__linkwithattr+arrayValues[i][j].myText+t431__linkclosetag+"</"+coltag+">"}else{t431__htmlpart+=t431__colwithattr+arrayValues[i][j].myText+"</"+coltag+">"}}else{t431__htmlpart+="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"+"</"+coltag+">"}}
t431__htmlpart+="</tr>"}
t431__htmlpart+="</"+t431__theadorbodytag+">";return t431__htmlpart};t431_parseData=function(t431__data){if(t431__data!=""&&typeof t431__data!='undefined')
{t431__data=t431__addBrTag(t431__data);var t431__arrayTable=new Array();var t431__arrayRow=new Array();var t431__curItem={myText:"",myHref:"",myHrefType:""};var t431__HasLink="";var t431__HasLinkWithSpace="";var t431__HasBtn="";var t431__HasBtnWithSpace="";var t431__EndOfLine="";for(var i=0;i<t431__data.length;i++)
{if(t431__data[i]==";"&&!((t431__data[i-1]&&(t431__data[i-1]=="t"))&&(t431__data[i-2]&&(t431__data[i-2]=="g"||t431__data[i-2]=="l"))&&(t431__data[i-3]&&(t431__data[i-3]=="&")))&&!((t431__data[i-1]&&(t431__data[i-1]=="p"))&&(t431__data[i-2]&&(t431__data[i-2]=="m"))&&(t431__data[i-3]&&(t431__data[i-3]=="a"))&&(t431__data[i-4]&&(t431__data[i-4]=="&")))){t431__arrayRow.push(t431__curItem);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace=""}else{if(t431__HasLink=="link="||t431__HasLinkWithSpace==" link="||t431__HasBtn=="button="||t431__HasBtnWithSpace==" button="){if(t431__curItem.myHref==""&&t431__HasLink=="link="){t431__curItem.myText=t431__curItem.myText.slice(0,-5);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasLinkWithSpace==" link="){t431__curItem.myText=t431__curItem.myText.slice(0,-6);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasBtn=="button="){t431__curItem.myText=t431__curItem.myText.slice(0,-7);t431__curItem.myHrefType="btn"}else{if(t431__curItem.myHref==""&&t431__HasBtnWithSpace==" button="){t431__curItem.myText=t431__curItem.myText.slice(0,-8);t431__curItem.myHrefType="btn"}}}}
t431__curItem.myHref+=(t431__data[i])}else{t431__curItem.myText+=(t431__data[i]);t431__HasLink=t431__checkSubstr("link=",t431__HasLink,t431__data[i]);t431__HasLinkWithSpace=t431__checkSubstr(" link=",t431__HasLinkWithSpace,t431__data[i]);t431__HasBtn=t431__checkSubstr("button=",t431__HasBtn,t431__data[i]);t431__HasBtnWithSpace=t431__checkSubstr(" button=",t431__HasBtnWithSpace,t431__data[i])}
t431__EndOfLine=t431__checkSubstr("<br />",t431__EndOfLine,t431__data[i]);if(t431__EndOfLine=="<br />"){if(t431__curItem.myHref){t431__curItem.myHref=t431__curItem.myHref.slice(0,-6)}else{t431__curItem.myText=t431__curItem.myText.slice(0,-6)}
t431__arrayRow.push(t431__curItem);t431__arrayTable.push(t431__arrayRow);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace="";t431__arrayRow=new Array()}}}
if(t431__arrayRow.length>0||t431__curItem.myText!=""){if(t431__curItem!=""){t431__arrayRow.push(t431__curItem)}
t431__arrayTable.push(t431__arrayRow)}}
return t431__arrayTable};t431__checkSubstr=function(t431__targetSubstr,t431__curSubstr,t431__curSymbol){if(!t431__curSubstr&&t431__curSymbol==t431__targetSubstr[0]){return t431__curSymbol}else{if(t431__curSubstr){for(var i=0;i<(t431__targetSubstr.length-1);i++){if(t431__curSubstr[t431__curSubstr.length-1]==t431__targetSubstr[i]&&t431__curSymbol==t431__targetSubstr[i+1]){return(t431__curSubstr+=t431__curSymbol)}}}}};t431__addBrTag=function(t431__oldStringItem){if(typeof t431__oldStringItem=='undefined')return;var t431__newStringItem="";for(var i=0;i<t431__oldStringItem.length;i++){if(t431__oldStringItem[i]=="\n"||t431__oldStringItem[i]=="\r"){t431__newStringItem+="<br />"}else{t431__newStringItem+=t431__oldStringItem[i]}}
return t431__newStringItem};function t449_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t449").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t449__beforeready')){el.finish();el.removeClass("t449__beforeready")}}else{el.stop();el.addClass("t449__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(!el.hasClass('t449__beforeready')){el.finish();el.addClass("t449__beforeready")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t449__beforeready")}}else{el.stop();el.removeClass("t449__beforeready")}}}})}}
function t552_init(recid,ratio){var t552__el=$("#rec"+recid),t552__image=t552__el.find(".t552__blockimg:first");t552__setHeight(recid,t552__image,ratio);var t552__doResize;$(window).resize(function(){clearTimeout(t552__doResize);t552__doResize=setTimeout(function(){t552__setHeight(recid,t552__image,ratio)},200)})}
function t552__setHeight(recid,image,ratio){$("#rec"+recid+" .t552__blockimg").css("height",Math.round(image.innerWidth()*ratio))}
function t599_init(recid){var el=$('#rec'+recid);if(el.find('.t599__title').length){t599_equalHeight(el.find('.t599__title'))}
if(el.find('.t599__descr').length){t599_equalHeight(el.find('.t599__descr'))}
if(el.find('.t599__price').length){t599_equalHeight(el.find('.t599__price'))}
if(el.find('.t599__subtitle').length){t599_equalHeight(el.find('.t599__subtitle'))}};function t599_equalHeight(element){var highestBox=0;element.css('height','');element.each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){element.css('height',highestBox)}else{element.css('height','')}}
function t706_onSuccessCallback(t706_form){localStorage.removeItem("tcart");delete window.tcart;tcart__loadLocalObj();$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});window.tcart_success='yes'}
function t776__init(recid){setTimeout(function(){t_prod__init(recid);t776_initPopup(recid)},500)}
function t776_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_sldsInit(recid+' #t776__product-'+lid_prod+'')});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();t776_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]')
el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t776_updateSlider(recid+' #t776__product-'+lid_prod+'');if(window.lazy=='y'){t_lazyload_update()}});if($('#record'+recid).length==0){t776_checkUrl(recid)}
t776_copyTypography(recid)}
function t776_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t776_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t776_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy=='y'){t_lazyload_update()}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').click(function(e){if(e.target==this){t776_closePopup()}});el.find('.t-popup__close, .t776__close-text').click(function(e){t776_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t776_closePopup()}})}
function t776_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t776_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t776_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t776__title').attr('style');var descrStyle=rec.find('.t776__descr').attr('style');rec.find('.t-popup .t776__title').attr("style",t776_removeSizeStyles(titleStyle));rec.find('.t-popup .t776__descr, .t-popup .t776__text').attr("style",t776_removeSizeStyles(descrStyle))}